# -*- coding: utf-8 -*-
"""Air pollution Monitoring using IOT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v91zbnUe6inJ6ffl7zWpkHfkyAW7q0i6
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import datetime 
import matplotlib.dates as md

from google.colab import files 
uploaded = files.upload()

df=pd.read_csv('Pollution.csv')
df.head()

df.drop("Entry_id",axis=1,inplace=True)
df.head()

#finding out pollution level at BowBazar by hourly update
plt.figure(figsize=(12,8))
plt.rcParams.update({'font.size':15})
x =pd.to_datetime(df['Created_at'])
y=df['BowBazar']
plt.plot_date(x, y)
plt.xlabel("Data & Hour")
plt.ylabel("Pollution Level")
plt.title("Hourly Pollution Level at BowBazar")

#finding out pollution level at Gariahat by hourly update
plt.figure(figsize=(12,8))
plt.rcParams.update({'font.size':15})
x =pd.to_datetime(df['Created_at'])
y=df['Gariahat']
plt.plot_date(x, y,color='green')
plt.xlabel("Data & Hour")
plt.ylabel("Pollution Level")
plt.title("Hourly Pollution Level at Gariahat")

#finding out pollution level at Esplanede by hourly update
plt.figure(figsize=(12,8))
plt.rcParams.update({'font.size':15})
x =pd.to_datetime(df['Created_at'])
y=df['Esplanede']
plt.plot_date(x, y,color='red')
plt.xlabel("Data & Hour")
plt.ylabel("Pollution Level")
plt.title("Hourly Pollution Level at Esplanede")

sns.jointplot(x="BowBazar",y="Gariahat",data=df,color='green')

sns.jointplot(x="BowBazar",y="Esplanede",data=df,color='red')

sns.jointplot(x="Esplanede",y="Gariahat",data=df,color='k')